name: ai574_NLP
channels:
  - conda-forge
  - main
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - jupyter

  # NLP work
  - nltk
  - scikit-learn
  - numpy

  # Web scraping
  - requests
  - beautifulsoup4

  # PDF scraping
  - pypdf2

  - pdfminer.six

  - pip:
    - python-dotenv
    - pymupdf
    - lxml
    - -e .